### ISSUE TITLE
no screenshot is taken when there is a remote exception

### ISSUE THREAD

**Issue by sglebs** [andreptb/fitnesse-selenium-slim#2]
My tests cause your fixture sent these:

```
127.0.0.1 - - [24/Jun/2015 13:22:16] "POST /wd/hub/session/1435162927068/element HTTP/1.1" 200 76
127.0.0.1 - - [24/Jun/2015 13:22:16] "POST /wd/hub/session/1435162927068/element/_NS%253A338/clear HTTP/1.1" 404 826
127.0.0.1 - - [24/Jun/2015 13:22:17] "GET /wd/hub/session/1435162927068/screenshot HTTP/1.1" 200 546
```

Note that I have not implemented clear yet. Therefore I see this exception in fitnesse:

```
    <html>
        <head>
            <title>Error: 404 Not Found</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 404 Not Found</h1>
            <p>Sorry, the requested URL <tt>&#039;http://localhost:5555/wd/hub/session/1435162927068/element/_NS%253A338/clear&#039;</tt>
               caused an error:</p>
            <pre>Not found: &#039;/wd/hub/session/1435162927068/element/_NS%3A338/clear&#039;</pre>
        </body>
    </html>
Command duration or timeout: 82 milliseconds
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'Marcio-Marchinis-MacBook-Pro-Silver.local', ip: '192.168.130.30', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_40'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{bundleId=com.apple.calculator, platform=ANY}]
Session ID: 1435162927068
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.8.0_40]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [rt.jar:1.8.0_40]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.8.0_40]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [rt.jar:1.8.0_40]
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204) [selenium-remote-driver-2.46.0.jar]
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156) [selenium-remote-driver-2.46.0.jar]
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605) [selenium-remote-driver-2.46.0.jar]
    at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:269) [selenium-remote-driver-2.46.0.jar]
    at org.openqa.selenium.remote.RemoteWebElement.clear(RemoteWebElement.java:114) [selenium-remote-driver-2.46.0.jar]
    at com.github.andreptb.fitnesse.SeleniumFixture.typeIn(SeleniumFixture.java:287) [file:/Users/mqm/git/fitnesse-selenium-slim/target/classes/]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_40]
    at java.lang.reflect.Method.invoke(Method.java:497) [rt.jar:1.8.0_40]
    at fitnesse.slim.fixtureInteraction.DefaultInteraction.methodInvoke(DefaultInteraction.java:81) [fitnesse-20150620.jar]
    at fitnesse.slim.MethodExecutor.callMethod(MethodExecutor.java:57) [fitnesse-20150620.jar]
    at fitnesse.slim.MethodExecutor.invokeMethod(MethodExecutor.java:38) [fitnesse-20150620.jar]
    at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:72) [fitnesse-20150620.jar]
    at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:20) [fitnesse-20150620.jar]
    at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:126) [fitnesse-20150620.jar]
    at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:104) [fitnesse-20150620.jar]
    at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35) [fitnesse-20150620.jar]
    at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29) [fitnesse-20150620.jar]
    at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49) [fitnesse-20150620.jar]
    at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43) [fitnesse-20150620.jar]
    at fitnesse.slim.ListExecutor.execute(ListExecutor.java:83) [fitnesse-20150620.jar]
    at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:85) [fitnesse-20150620.jar]
    at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:78) [fitnesse-20150620.jar]
    at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:57) [fitnesse-20150620.jar]
    at fitnesse.slim.SlimServer.serve(SlimServer.java:42) [fitnesse-20150620.jar]
    at fitnesse.slim.SlimService.handle(SlimService.java:186) [fitnesse-20150620.jar]
    at fitnesse.slim.SlimService.acceptOne(SlimService.java:194) [fitnesse-20150620.jar]
    at fitnesse.slim.SlimService.accept(SlimService.java:156) [fitnesse-20150620.jar]
    at fitnesse.slim.SlimService.startWithFactory(SlimService.java:77) [fitnesse-20150620.jar]
    at fitnesse.slim.SlimService.main(SlimService.java:57) [fitnesse-20150620.jar]
```

But the screenshot is not shown.

**Comment by sglebs** [comment]
(can't reproduce)
